# Generated by Django 6.0.3 on 2026-03-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_profile_cover_image_certificate_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='posts/documents/'),
        ),
    ]
